name = "cLean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["CLean"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "scilean"
scope = "git"
git = "https://github.com/lecopivo/SciLean"
rev = "v4.20.1"


[[lean_lib]]
name = "CLean"
